inputs_dir: ./_inputs
results_dir: ./_results

ignores:
  inputs:
    # []
    - dev
    # - stage
    - test
    - prod
  db:
    - postgres
    - rdsadmin
    - template0
    - template1
  role:
    - rdstopmgr
    - rdsrepladmin
    - rdsadmin
    - rds_superuser
    - rds_replication
    - rds_password
    - rds_iam
    - rds_ad
    - datadog_agent
    - change_owner
  schema:
    - pg_catalog
    - information_schema
    - datadog
  table:
    - pg_stat_statements
  result_table_column_databases:
    []
    # - Env
    # - Instance name
    # - Database
    # - Owner
    # - Access privileges
    # - Schema
    # - Table
    # - Table owner
    # - Access privileges
    # - Column privileges
    # - Policies
  result_table_column_roles:
    []
    # - Env
    # - Instance name
    # - Role name
    # - rolbypassrls
    # - rolcanlogin
    # - rolconnlimit
    # - rolcreatedb
    # - rolcreaterole
    # - rolinherit
    # - rolreplication
    # - rolsuper
    # - rolvaliduntil
    # - memberof
