name: Bump Package Version
"on":
  push:
    branches:
      - master
jobs:
  bump-version:
    name: Bump Package Version
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip
      - name: Install dependencies
        run: pip install commitizen pylint
      - name: Cache pre-commit
        id: cache-pre-commit
        uses: actions/cache@v4
        env:
          cache-name: cache-pre-commit
        with:
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
          path: ~/.cache/pre-commit
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
      - name: Bump version
        id: bump
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          cz bump --yes
        continue-on-error: true
      - name: Push changes
        if: steps.bump.outcome == 'success'
        run: git push && git push --tags
