name: PR checks
"on":
  pull_request:
    branches:
      - master
jobs:
  pre-commit:
    name: Run pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip
      - name: Install dependencies
        run: pip install pylint
      - name: Cache pre-commit
        id: cache-pre-commit
        uses: actions/cache@v4
        env:
          cache-name: cache-pre-commit
        with:
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
          path: ~/.cache/pre-commit
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
